import { timestamp, uuid } from 'drizzle-orm/pg-core';

/** Every table's primary key: a random UUID generated by Postgres. */
export function id() {
  return uuid().primaryKey().defaultRandom();
}

/** A system timestamp: timestamptz, defaults to now(), never null (created_at, submitted_at, …). */
export function timestamptzNow() {
  return timestamp({ withTimezone: true }).notNull().defaultNow();
}
